apiVersion: v1
kind: Namespace
metadata:
  name: ns-dev
  labels:
    env: dev
    app: frontend
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-prd
  labels:
    env: prd
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-frontend
  labels:
    env: dev
    app: frontend
  namespace: ns-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev
      app: frontend
  template:
    metadata:
      labels:
        env: dev
        app: frontend
      namespace: dev
    spec:
      containers:
        - name: server-web
          image: nginx:alpine
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-frontend
  labels:
    env: prd
    app: frontend
  namespace: prd
spec:
  replicas: 3
  selector:
    matchLabels:
      env: prd
      app: frontend
    namespace: prd
  template:
    metadata:
      labels:
        env: prd
        app: frontend
      namespace: prd
    spec:
      containers:
        - name: server-web
          image: nginx:alpine          