services:
  server-nginx:
    image: nginx:alpine
    container_name: server-nginx
    ports:
      - 80:80
    working_dir: /app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./www:/app:ro
