apiVersion: v1
kind: Service
metadata:
  name: svc-node-port-ip
spec:
  type: NodePort
  selector:
    env: dev
    app: frontend
  ports:
    - nodePort: 31000
      port: 3000
      targetPort: 80
      protocol: TCP
      name: port-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-frontend
  labels:
    env: dev
    app: frontend
spec:
  replicas: 5
  selector:
    matchLabels:
      env: dev
      app: frontend
  template:
    metadata:
      labels:
        env: dev
        app: frontend
    spec:
      containers:
        - name: server-web
          image: nginx:alpine