services:
  server-web:
    image: nginx:stable-alpine
    container_name: server-web
    ports:
      - "8090:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  php-fpm:
    build:
      dockerfile: php.dockerfile
      context: ./dockerfiles
    container_name: php-fpm
    volumes:
      - ./src:/var/www/html

  mysql:
    image: mysql:8
    container_name: mysql
    env_file:
      - ./env/mysql.env

  # Utilitarios
  composer:
    build:
      dockerfile: composer.dockerfile
      context: ./dockerfiles
    volumes:
      - ./src:/var/www/html

  artisan:
    build: 
      dockerfile: php.dockerfile
      context: ./dockerfiles
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]

  npm:
    image: node:18.19.1-alpine
    container_name: npm
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    entrypoint: ["npm"]