apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      env: dev
      app: frontend
  template:
    metadata:
      labels:
        env: dev
        app: frontend
    spec:
      containers:
        - name: frontend
          image: cursodocker15.azurecr.io/frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: cm-parameters
                  key: FRONTEND_PORT
            - name: BACKEND1
              valueFrom:
                configMapKeyRef:
                  name: cm-parameters
                  key: BACKEND1_URL          
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3                    