apiVersion: v1
kind: Namespace
metadata:
  name: ns-dev
  labels:
    env: dev
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-parameters
  namespace: ns-dev
data:
  db_host: ZGF0YWJhc2UxLmNvbXBhbnkuY29t
  db_port: MzMwNg==
  db_user: dXNlcjEyMw==
  db_pass: MTIzNDU2Nzg5MA==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-backend
  namespace: ns-dev
  labels:
    env: dev
spec:
  replicas: 5
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
        - name: container01
          image: nginx:alpine
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: secret-parameters
                  key: db_host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: secret-parameters
                  key: db_port
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: secret-parameters
                  key: db_user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: secret-parameters
                  key: db_pass                                  
            

