apiVersion: v1
kind: Namespace
metadata:
  name: ns-dev
  labels:
    env: dev
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-parameters
  namespace: ns-dev
data:
  api_url: https://dev-api.mycompany.com
  kafka_url: http://svc-kafka:9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-backend
  namespace: ns-dev
  labels:
    env: dev
spec:
  replicas: 5
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
        - name: container01
          image: nginx:alpine
          env:
            - name: KAFKA_BROKERS_NUM
              value: "1"
            - name: API_URL_APP
              valueFrom:
                configMapKeyRef:
                  name: cm-parameters
                  key: api_url
            - name: KAFKA_URL_APP
              valueFrom:
                configMapKeyRef:
                  name: cm-parameters
                  key: kafka_url
            

